# Generated by Django 4.2.26 on 2025-11-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatorprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required before operator can log in'),
        ),
    ]
