# Generated by Django 4.2.26 on 2025-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='qr_code',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
