# Generated by Django 4.2.7 on 2025-11-19 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_users',
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operators.operatoruser')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_assignments', to='routes.route')),
            ],
            options={
                'db_table': 'operator_assignments',
            },
        ),
        migrations.AddIndex(
            model_name='operatoruser',
            index=models.Index(fields=['is_active'], name='operator_us_is_acti_c90ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['operator', 'is_active'], name='operator_as_operato_eea557_idx'),
        ),
        migrations.AddIndex(
            model_name='operatorassignment',
            index=models.Index(fields=['route'], name='operator_as_route_i_ee04d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatorassignment',
            unique_together={('operator', 'route')},
        ),
    ]
