# Generated by Django 4.2.7 on 2025-11-19 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_routes', to='routes.district')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_routes', to='routes.district')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['name'], name='districts_name_961bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['origin', 'destination'], name='routes_origin__4f7e33_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['is_active'], name='routes_is_acti_9ece4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('origin', 'destination')},
        ),
    ]
