# Generated by Django 4.2.7 on 2025-11-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Ticket price in RWF', max_digits=10),
        ),
    ]
