# Generated by Django 4.2.7 on 2025-11-19 15:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        ('buses', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_recurrences', to='buses.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_recurrences', to='routes.route')),
            ],
            options={
                'db_table': 'schedule_recurrences',
            },
        ),
        migrations.CreateModel(
            name='ScheduleOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='bookings.schedulerecurrence')),
            ],
            options={
                'db_table': 'schedule_occurrences',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money'), ('cash', 'Cash')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='operators.operatoruser')),
                ('schedule_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.scheduleoccurrence')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.AddIndex(
            model_name='schedulerecurrence',
            index=models.Index(fields=['route', 'is_active'], name='schedule_re_route_i_990e69_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerecurrence',
            index=models.Index(fields=['departure_time'], name='schedule_re_departu_2c8d32_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleoccurrence',
            index=models.Index(fields=['date', 'status'], name='schedule_oc_date_afe76c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleoccurrence',
            index=models.Index(fields=['recurrence', 'date'], name='schedule_oc_recurre_367539_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleoccurrence',
            index=models.Index(fields=['departure_time', 'date'], name='schedule_oc_departu_eba2e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleoccurrence',
            unique_together={('recurrence', 'date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['phone_number'], name='bookings_phone_n_2afe4e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_status_51373b_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['schedule_occurrence', 'status'], name='bookings_schedul_8108de_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='bookings_created_118d3e_idx'),
        ),
    ]
